from app.models.inverter_model import InverterModel, InverterPoint
from app.services.ingeteam_command_service import INGETEAM_UNIT_COMMAND_DRIVER


INGETEAM_MODELS = [
    "Ingecon SUN 250 TL",
    "Ingecon SUN 315HE TL",
    "Ingecon SUN 365HE TL",
    "Ingecon SUN 375 TL",
    "Ingecon SUN 400HE TL",
    "Ingecon SUN 420HE TL",
    "Ingecon SUN 500 TL",
    "Ingecon SUN 500HE TL",
    "Ingecon SUN 550HE TL",
    "Ingecon SUN 600HE TL",
    "Ingecon SUN 625HE TL",
    "Ingecon SUN 630HE TL",
    "Ingecon SUN730HE TL",
    "Ingecon SUN 800HE TL",
    "Ingecon SUN 840HE TL",
]

INGETEAM_COMMAND_CODE_MAP = {
    0: "No command",
    1: "Change tan phi target",
    3: "Change Pac injection derating",
    5: "Stop inverter",
    6: "Start inverter",
    7: "Standby inverter",
    9: "Change reactive power target",
    10: "Change cos phi target",
    11: "Disable reactive targets",
    12: "External signal thresholds",
    15: "Grid support operating mode",
    16: "Digital outputs relays",
    19: "Inverter operation mode",
    23: "Manual Pac ramp",
    24: "Battery commands",
    25: "Change strategy mode",
    26: "Battery control values",
    28: "Pac absorption derating",
    29: "Pac injection derating by DC source",
    30: "Start autotest",
    31: "Stop autotest",
    32: "Start fan test",
    33: "Disable network algorithms",
}

INGETEAM_EXTERNAL_SIGNAL_MAP = {
    0: "Permissive thresholds",
    1: "Restrictive thresholds",
}

INGETEAM_STRATEGY_MODE_MAP = {
    0: "Stand alone",
    1: "Grid support",
    2: "Back up",
    3: "Self-consumption",
}

INGETEAM_OPERATION_MODE_MAP = {
    0: "Current source PQ control",
    1: "Current source Vbat control",
    2: "Voltage source V/f control",
    3: "Voltage source transition to current source",
    4: "Current source Vbat control with blackstart",
}

INGETEAM_GRID_SUPPORT_MODE_MAP = {
    0: "On-grid current source",
    1: "Off-grid voltage source VLOADS + VGRID",
    2: "Off-grid voltage source only VLOADS",
}

INGETEAM_DIGITAL_OUTPUT_MAP = {
    0: "Open digital output relay 1",
    1: "Close digital output relay 1",
    2: "Open digital output relay 2",
    3: "Close digital output relay 2",
}

INGETEAM_BATTERY_COMMAND_MAP = {
    0: "Stop lithium battery",
    1: "Start lithium battery",
    2: "Standby lithium battery",
    3: "Stop equalization",
    4: "Start equalization",
    5: "Start emergency charge",
    6: "Wake-up lithium battery",
}

INGETEAM_POWER_REDUCTION_BITS = {
    0: "Limitazione potenza attiva presente",
    1: "Limitazione potenza da Modbus",
    2: "Riduzione per alta frequenza",
    3: "Riduzione dopo guasto rete",
    4: "Riduzione per Vdc alta",
    5: "Riduzione per alta temperatura",
    6: "Riduzione per Vac alta",
    7: "Riduzione per temperatura PCB alta",
    8: "Consigna reattiva attiva",
    9: "Riduzione per Vdc minima",
    10: "Riduzione per ventola ferma",
}

INGETEAM_STOP_REASON_MAP = {
    1: "VIN alta",
    2: "Frequenza rete fuori range",
    3: "Tensione rete fuori range",
    4: "Varistori",
    5: "Isolamento DC",
    6: "Corrente AC efficace fuori range",
    7: "Temperatura alta",
    8: "Motivo 01",
    9: "Configurazione",
    10: "Arresto manuale",
    11: "Bassa tensione ingresso FV",
    12: "HW DESCX2",
    13: "Frama 3",
    14: "Massima Iac istantanea",
    15: "Caricamento firmware",
    16: "Motivo 03",
    17: "Motivo 04",
    18: "Errore lettura ADC",
    19: "Consumo potenza",
    20: "Fusibile DC",
    21: "Temperatura ausiliaria",
    22: "Disconnessione AC",
    23: "Magnetotermico",
    24: "Contattore",
    25: "Reset watchdog",
    26: "PI analogico in saturazione",
    27: "Latenza ADC",
    28: "Errore fatale",
    29: "Frama 1",
    30: "Frama 2",
}


def telemetry_point(
    key: str,
    label: str,
    address: int,
    length: int,
    datatype: str,
    *,
    register_type: str = "holding",
    scale: float = 1.0,
    unit: str = "",
    section: str,
    visible: bool = True,
    enum_map: dict[int, str] | None = None,
    bitmask_labels: dict[int, str] | None = None,
    display_format: str | None = None,
    display_width: int | None = None,
    summary_metric: str | None = None,
) -> InverterPoint:
    protocol_meta: dict[str, object] = {"section": section}
    if enum_map is not None:
        protocol_meta["enum_map"] = enum_map
    if bitmask_labels is not None:
        protocol_meta["bitmask_labels"] = bitmask_labels
    if display_format is not None:
        protocol_meta["display_format"] = display_format
    if display_width is not None:
        protocol_meta["display_width"] = display_width
    if summary_metric is not None:
        protocol_meta["summary_metric"] = summary_metric

    return InverterPoint(
        key=key,
        label=label,
        kind="telemetry",
        register_type=register_type,
        address=address,
        length=length,
        datatype=datatype,
        scale=scale,
        unit=unit,
        visible=visible,
        protocol_meta=protocol_meta,
    )


def command_point(
    key: str,
    label: str,
    *,
    scale: float = 1.0,
    unit: str = "",
    min_value: float | None = None,
    max_value: float | None = None,
    step: float | None = None,
    command_code: int,
    command_words: list[dict[str, object]] | None = None,
    section: str,
) -> InverterPoint:
    protocol_meta: dict[str, object] = {
        "driver": INGETEAM_UNIT_COMMAND_DRIVER,
        "section": section,
        "command_code": command_code,
        "command_words": command_words or [],
        "force_multi_write": True,
    }
    if min_value is not None:
        protocol_meta["min_value"] = min_value
    if max_value is not None:
        protocol_meta["max_value"] = max_value
    if step is not None:
        protocol_meta["step"] = step

    return InverterPoint(
        key=key,
        label=label,
        kind="command",
        register_type="holding",
        address=1000,
        length=1 + len(command_words or []),
        datatype="uint16",
        scale=scale,
        unit=unit,
        writable=True,
        protocol_meta=protocol_meta,
    )


def build_ingeteam_telemetry() -> list[InverterPoint]:
    return [
        telemetry_point(
            "total_energy_kwh",
            "Energia totale prodotta",
            0,
            2,
            "uint32",
            register_type="input",
            unit="kWh",
            section="Monitoraggio live",
            summary_metric="total_energy_kwh",
        ),
        telemetry_point(
            "runtime_hours",
            "Ore di funzionamento",
            2,
            2,
            "uint32",
            register_type="input",
            unit="h",
            section="Monitoraggio live",
        ),
        telemetry_point(
            "grid_connection_count",
            "Numero connessioni alla rete",
            4,
            2,
            "uint32",
            register_type="input",
            section="Monitoraggio live",
        ),
        telemetry_point(
            "inverter_alarms_raw",
            "Allarmi inverter",
            7,
            1,
            "uint16",
            register_type="input",
            section="Stato e allarmi",
            display_format="hex",
            display_width=4,
        ),
        telemetry_point(
            "dc_voltage_v",
            "Tensione DC campo FV",
            8,
            1,
            "uint16",
            register_type="input",
            unit="V",
            section="Monitoraggio live",
        ),
        telemetry_point(
            "dc_current_a",
            "Corrente DC campo FV",
            9,
            1,
            "uint16",
            register_type="input",
            unit="A",
            section="Monitoraggio live",
        ),
        telemetry_point(
            "ac_voltage_v",
            "Tensione rete L1",
            10,
            1,
            "uint16",
            register_type="input",
            unit="V",
            section="Rete AC",
        ),
        telemetry_point(
            "ac_voltage_l2_v",
            "Tensione rete L2",
            11,
            1,
            "uint16",
            register_type="input",
            unit="V",
            section="Rete AC",
        ),
        telemetry_point(
            "ac_voltage_l3_v",
            "Tensione rete L3",
            12,
            1,
            "uint16",
            register_type="input",
            unit="V",
            section="Rete AC",
        ),
        telemetry_point(
            "ac_current_a",
            "Corrente rete L1",
            13,
            1,
            "uint16",
            register_type="input",
            unit="A",
            section="Rete AC",
        ),
        telemetry_point(
            "ac_current_l2_a",
            "Corrente rete L2",
            14,
            1,
            "uint16",
            register_type="input",
            unit="A",
            section="Rete AC",
        ),
        telemetry_point(
            "ac_current_l3_a",
            "Corrente rete L3",
            15,
            1,
            "uint16",
            register_type="input",
            unit="A",
            section="Rete AC",
        ),
        telemetry_point(
            "cos_phi",
            "Cos(phi)",
            16,
            1,
            "int16",
            register_type="input",
            scale=0.001,
            section="Rete AC",
        ),
        telemetry_point(
            "active_power_kw",
            "Potenza AC attiva",
            18,
            1,
            "int16",
            register_type="input",
            scale=0.01,
            unit="kW",
            section="Potenza",
            summary_metric="power_kw",
        ),
        telemetry_point(
            "grid_frequency_hz",
            "Frequenza di rete",
            19,
            1,
            "uint16",
            register_type="input",
            scale=0.01,
            unit="Hz",
            section="Rete AC",
        ),
        telemetry_point(
            "resettable_energy_kwh",
            "Energia resettabile",
            58,
            2,
            "uint32",
            register_type="input",
            unit="kWh",
            section="Contatori",
        ),
        telemetry_point(
            "instantaneous_inverter_alarms_raw",
            "Allarmi inverter istantanei",
            64,
            2,
            "uint32",
            register_type="input",
            section="Stato e allarmi",
            display_format="hex",
            display_width=8,
        ),
        telemetry_point(
            "maintained_inverter_alarms_raw",
            "Allarmi inverter mantenuti",
            66,
            2,
            "uint32",
            register_type="input",
            section="Stato e allarmi",
            display_format="hex",
            display_width=8,
        ),
        telemetry_point(
            "reactive_power_kvar",
            "Potenza reattiva",
            68,
            1,
            "int16",
            register_type="input",
            scale=0.01,
            unit="kVAr",
            section="Potenza",
        ),
        telemetry_point(
            "temperature_c",
            "Temperatura elettronica di potenza",
            71,
            1,
            "int16",
            register_type="input",
            unit="C",
            section="Termico",
            summary_metric="temperature_c",
        ),
        telemetry_point(
            "control_temperature_c",
            "Temperatura elettronica di controllo",
            72,
            1,
            "int16",
            register_type="input",
            unit="C",
            section="Termico",
        ),
        telemetry_point(
            "status",
            "Stato inverter",
            73,
            1,
            "uint16",
            register_type="input",
            section="Stato e allarmi",
            summary_metric="status",
            display_format="hex",
            display_width=4,
        ),
        telemetry_point(
            "vpv_negative_to_ground_v",
            "Tensione FV negativo-terra",
            74,
            1,
            "uint16",
            register_type="input",
            unit="V",
            section="Ingresso FV",
        ),
        telemetry_point(
            "vpv_positive_to_ground_v",
            "Tensione FV positivo-terra",
            75,
            1,
            "uint16",
            register_type="input",
            unit="V",
            section="Ingresso FV",
        ),
        telemetry_point(
            "power_rating_kw",
            "Potenza nominale",
            76,
            1,
            "uint16",
            register_type="input",
            scale=0.01,
            unit="kW",
            section="Targa",
        ),
        telemetry_point(
            "latest_stop_reason",
            "Ultimo motivo di arresto",
            83,
            1,
            "uint16",
            register_type="input",
            section="Stato e allarmi",
            enum_map=INGETEAM_STOP_REASON_MAP,
        ),
        telemetry_point(
            "power_reduction_status",
            "Cause riduzione potenza",
            116,
            1,
            "uint16",
            register_type="input",
            section="Derating e limiti",
            bitmask_labels=INGETEAM_POWER_REDUCTION_BITS,
        ),
        telemetry_point(
            "command_code",
            "Command code",
            1000,
            1,
            "uint16",
            section="Unit commands",
            enum_map=INGETEAM_COMMAND_CODE_MAP,
            visible=False,
        ),
        telemetry_point("command_data_1_raw", "Command data 1 raw", 1001, 1, "uint16", section="Unit commands", display_format="hex", display_width=4, visible=False),
        telemetry_point("command_data_2_raw", "Command data 2 raw", 1002, 1, "uint16", section="Unit commands", display_format="hex", display_width=4, visible=False),
        telemetry_point(
            "active_power_reduction_reference_percent",
            "Active power reduction reference",
            1005,
            1,
            "int16",
            scale=100.0 / 32767.0,
            unit="%Pn",
            section="Setpoints",
            visible=False,
        ),
        telemetry_point(
            "tan_phi_reference",
            "Tan(phi) reference",
            1006,
            1,
            "int16",
            scale=1.0 / 32767.0,
            section="Setpoints",
            visible=False,
        ),
        telemetry_point(
            "reactive_power_reference_percent",
            "Reactive power reduction reference",
            1007,
            1,
            "int16",
            scale=100.0 / 32767.0,
            unit="%Qmax",
            section="Setpoints",
            visible=False,
        ),
        telemetry_point(
            "cos_phi_target",
            "Cos(phi) target",
            1008,
            1,
            "int16",
            scale=1.0 / 32767.0,
            section="Setpoints",
            visible=False,
        ),
        telemetry_point(
            "external_signal_threshold_mode",
            "External signal thresholds",
            1009,
            1,
            "uint16",
            section="Modes",
            enum_map=INGETEAM_EXTERNAL_SIGNAL_MAP,
            visible=False,
        ),
        telemetry_point(
            "strategy_mode",
            "Inverter strategy mode",
            1010,
            1,
            "uint16",
            section="Modes",
            enum_map=INGETEAM_STRATEGY_MODE_MAP,
            visible=False,
        ),
        telemetry_point(
            "inverter_operation_mode",
            "Inverter operation mode",
            1011,
            1,
            "uint16",
            section="Modes",
            enum_map=INGETEAM_OPERATION_MODE_MAP,
            visible=False,
        ),
        telemetry_point(
            "ac_power_limit_w",
            "AC power limit",
            1012,
            2,
            "uint32",
            unit="W",
            section="Limits",
            visible=False,
        ),
        telemetry_point(
            "vbat_voltage_reference_v",
            "VBAT voltage reference",
            1014,
            1,
            "uint16",
            unit="V",
            section="References",
            visible=False,
        ),
        telemetry_point(
            "frequency_reference_hz",
            "Frequency reference",
            1015,
            1,
            "uint16",
            scale=0.01,
            unit="Hz",
            section="References",
            visible=False,
        ),
        telemetry_point(
            "ac_rms_voltage_reference_v",
            "AC RMS voltage reference",
            1016,
            1,
            "uint16",
            unit="V",
            section="References",
            visible=False,
        ),
    ]


def build_ingeteam_commands() -> list[InverterPoint]:
    return [
        command_point(
            "tan_phi_target",
            "Tan(phi) target",
            command_code=1,
            command_words=[{"source": "value", "encoding": "fraction_to_int16_32767"}],
            min_value=-0.75,
            max_value=0.75,
            step=0.001,
            section="Reactive power",
        ),
        command_point(
            "active_power_limit",
            "Active power injection derating",
            command_code=3,
            command_words=[{"source": "value", "encoding": "percent_to_int16_32767"}],
            min_value=0.0,
            max_value=100.0,
            step=0.1,
            unit="%",
            section="Active power",
        ),
        command_point(
            "reactive_power_target_percent",
            "Reactive power target",
            command_code=9,
            command_words=[{"source": "value", "encoding": "percent_to_int16_32767"}],
            min_value=-100.0,
            max_value=100.0,
            step=0.1,
            unit="%",
            section="Reactive power",
        ),
        command_point(
            "cos_phi_target",
            "Cos(phi) target",
            command_code=10,
            command_words=[{"source": "value", "encoding": "fraction_to_int16_32767"}],
            min_value=-1.0,
            max_value=1.0,
            step=0.001,
            section="Reactive power",
        ),
        command_point(
            "external_signal_threshold_mode_set",
            "External signal thresholds",
            command_code=12,
            command_words=[{"source": "value", "encoding": "raw_uint16"}],
            min_value=0.0,
            max_value=1.0,
            step=1.0,
            section="Modes",
        ),
        command_point(
            "grid_support_operating_mode",
            "Grid support operating mode",
            command_code=15,
            command_words=[{"source": "value", "encoding": "raw_uint16"}],
            min_value=0.0,
            max_value=2.0,
            step=1.0,
            section="Modes",
        ),
        command_point(
            "digital_output_relays",
            "Digital output relays",
            command_code=16,
            command_words=[{"source": "value", "encoding": "raw_uint16"}],
            min_value=0.0,
            max_value=3.0,
            step=1.0,
            section="Digital outputs",
        ),
        command_point(
            "inverter_operation_mode_set",
            "Inverter operation mode",
            command_code=19,
            command_words=[{"source": "value", "encoding": "raw_uint16"}],
            min_value=0.0,
            max_value=4.0,
            step=1.0,
            section="Modes",
        ),
        command_point(
            "manual_pac_ramp_w_per_s",
            "Manual Pac ramp",
            command_code=23,
            command_words=[{"source": "value", "encoding": "raw_uint16"}],
            min_value=0.0,
            max_value=32767.0,
            step=1.0,
            unit="W/s",
            section="Active power",
        ),
        command_point(
            "battery_command",
            "Battery command",
            command_code=24,
            command_words=[{"source": "value", "encoding": "raw_uint16"}],
            min_value=0.0,
            max_value=6.0,
            step=1.0,
            section="Battery",
        ),
        command_point(
            "strategy_mode_set",
            "Strategy mode",
            command_code=25,
            command_words=[{"source": "value", "encoding": "raw_uint16"}],
            min_value=0.0,
            max_value=3.0,
            step=1.0,
            section="Modes",
        ),
        command_point(
            "battery_charge_current_a",
            "Battery charge current",
            command_code=26,
            command_words=[
                {"source": "fixed", "value": 0, "encoding": "raw_uint16"},
                {"source": "value", "encoding": "scaled_uint16"},
            ],
            min_value=0.0,
            max_value=50.0,
            step=1.0,
            unit="A",
            section="Battery",
        ),
        command_point(
            "battery_discharge_current_a",
            "Battery discharge current",
            command_code=26,
            command_words=[
                {"source": "fixed", "value": 1, "encoding": "raw_uint16"},
                {"source": "value", "encoding": "scaled_uint16"},
            ],
            min_value=0.0,
            max_value=50.0,
            step=1.0,
            unit="A",
            section="Battery",
        ),
        command_point(
            "battery_charge_voltage_v",
            "Battery charge voltage",
            command_code=26,
            command_words=[
                {"source": "fixed", "value": 2, "encoding": "raw_uint16"},
                {"source": "value", "encoding": "scaled_uint16"},
            ],
            min_value=45.0,
            max_value=450.0,
            step=1.0,
            unit="V",
            section="Battery",
        ),
        command_point(
            "battery_soc_percent",
            "Battery SOC",
            command_code=26,
            command_words=[
                {"source": "fixed", "value": 3, "encoding": "raw_uint16"},
                {"source": "value", "encoding": "scaled_uint16"},
            ],
            min_value=0.0,
            max_value=100.0,
            step=1.0,
            unit="%",
            section="Battery",
        ),
        command_point(
            "battery_soc_max_percent",
            "Battery SOC max",
            command_code=26,
            command_words=[
                {"source": "fixed", "value": 4, "encoding": "raw_uint16"},
                {"source": "value", "encoding": "scaled_uint16"},
            ],
            min_value=0.0,
            max_value=100.0,
            step=1.0,
            unit="%",
            section="Battery",
        ),
        command_point(
            "battery_soc_grid_percent",
            "Battery SOC grid",
            command_code=26,
            command_words=[
                {"source": "fixed", "value": 5, "encoding": "raw_uint16"},
                {"source": "value", "encoding": "scaled_uint16"},
            ],
            min_value=0.0,
            max_value=100.0,
            step=1.0,
            unit="%",
            section="Battery",
        ),
        command_point(
            "battery_soc_min_percent",
            "Battery SOC min",
            command_code=26,
            command_words=[
                {"source": "fixed", "value": 6, "encoding": "raw_uint16"},
                {"source": "value", "encoding": "scaled_uint16"},
            ],
            min_value=0.0,
            max_value=100.0,
            step=1.0,
            unit="%",
            section="Battery",
        ),
        command_point(
            "battery_soc_reconnect_percent",
            "Battery SOC reconnect",
            command_code=26,
            command_words=[
                {"source": "fixed", "value": 7, "encoding": "raw_uint16"},
                {"source": "value", "encoding": "scaled_uint16"},
            ],
            min_value=0.0,
            max_value=100.0,
            step=1.0,
            unit="%",
            section="Battery",
        ),
        command_point(
            "battery_soc_shutdown_percent",
            "Battery SOC shutdown",
            command_code=26,
            command_words=[
                {"source": "fixed", "value": 8, "encoding": "raw_uint16"},
                {"source": "value", "encoding": "scaled_uint16"},
            ],
            min_value=0.0,
            max_value=100.0,
            step=1.0,
            unit="%",
            section="Battery",
        ),
        command_point(
            "battery_charge_power_from_grid_w",
            "Battery charge power from grid",
            command_code=26,
            command_words=[
                {"source": "fixed", "value": 9, "encoding": "raw_uint16"},
                {"source": "value", "encoding": "scaled_uint16"},
            ],
            min_value=0.0,
            max_value=6000.0,
            step=1.0,
            unit="W",
            section="Battery",
        ),
        command_point(
            "battery_grid_power_w",
            "Battery grid power",
            command_code=26,
            command_words=[
                {"source": "fixed", "value": 10, "encoding": "raw_uint16"},
                {"source": "value", "encoding": "scaled_int16"},
            ],
            min_value=-6000.0,
            max_value=6000.0,
            step=1.0,
            unit="W",
            section="Battery",
        ),
        command_point(
            "battery_discharge_voltage_v",
            "Battery discharge voltage",
            command_code=26,
            command_words=[
                {"source": "fixed", "value": 11, "encoding": "raw_uint16"},
                {"source": "value", "encoding": "scaled_uint16"},
            ],
            min_value=40.0,
            max_value=450.0,
            step=1.0,
            unit="V",
            section="Battery",
        ),
        command_point(
            "battery_voltage_feedback_x10_v",
            "Battery voltage feedback x10",
            command_code=26,
            command_words=[
                {"source": "fixed", "value": 12, "encoding": "raw_uint16"},
                {"source": "value", "encoding": "scaled_uint16"},
            ],
            min_value=0.0,
            max_value=450.0,
            step=0.1,
            scale=0.1,
            unit="V",
            section="Battery",
        ),
        command_point(
            "battery_current_feedback_a",
            "Battery current feedback",
            command_code=26,
            command_words=[
                {"source": "fixed", "value": 13, "encoding": "raw_uint16"},
                {"source": "value", "encoding": "scaled_int16"},
            ],
            min_value=-50.0,
            max_value=50.0,
            step=1.0,
            unit="A",
            section="Battery",
        ),
        command_point(
            "battery_temperature_feedback_c",
            "Battery temperature feedback",
            command_code=26,
            command_words=[
                {"source": "fixed", "value": 14, "encoding": "raw_uint16"},
                {"source": "value", "encoding": "scaled_int16"},
            ],
            min_value=-20.0,
            max_value=80.0,
            step=0.1,
            scale=0.1,
            unit="C",
            section="Battery",
        ),
        command_point(
            "battery_voltage_feedback_x100_v",
            "Battery voltage feedback x100",
            command_code=26,
            command_words=[
                {"source": "fixed", "value": 15, "encoding": "raw_uint16"},
                {"source": "value", "encoding": "scaled_uint16"},
            ],
            min_value=0.0,
            max_value=320.0,
            step=0.01,
            scale=0.01,
            unit="V",
            section="Battery",
        ),
        command_point(
            "pac_absorption_derating_pv_grid_percent",
            "Pac absorption derating (PV + grid)",
            command_code=28,
            command_words=[
                {"source": "value", "encoding": "percent_to_int16_32767"},
                {"source": "fixed", "value": 0, "encoding": "raw_uint16"},
            ],
            min_value=0.0,
            max_value=100.0,
            step=0.1,
            unit="%",
            section="Active power",
        ),
        command_point(
            "pac_absorption_derating_grid_only_percent",
            "Pac absorption derating (grid only)",
            command_code=28,
            command_words=[
                {"source": "value", "encoding": "percent_to_int16_32767"},
                {"source": "fixed", "value": 1, "encoding": "raw_uint16"},
            ],
            min_value=0.0,
            max_value=100.0,
            step=0.1,
            unit="%",
            section="Active power",
        ),
        command_point(
            "active_power_limit_battery_pv_percent",
            "Pac injection derating (battery + PV)",
            command_code=29,
            command_words=[
                {"source": "value", "encoding": "percent_to_int16_32767"},
                {"source": "fixed", "value": 0, "encoding": "raw_uint16"},
            ],
            min_value=0.0,
            max_value=100.0,
            step=0.1,
            unit="%",
            section="Active power",
        ),
        command_point(
            "active_power_limit_pv_only_percent",
            "Pac injection derating (PV only)",
            command_code=29,
            command_words=[
                {"source": "value", "encoding": "percent_to_int16_32767"},
                {"source": "fixed", "value": 1, "encoding": "raw_uint16"},
            ],
            min_value=0.0,
            max_value=100.0,
            step=0.1,
            unit="%",
            section="Active power",
        ),
    ]


def build_ingeteam_models(protocol: str, transport: str) -> list[InverterModel]:
    if protocol == "modbus_tcp":
        defaults = {
            "host": "127.0.0.1",
            "port": 502,
            "unit_id": 1,
            "timeout_seconds": 2,
            "retries": 1,
            "poll_interval_seconds": 15,
            "test_register": 19,
            "test_count": 1,
            "test_function": "input",
            "max_registers_per_request": 32,
            "inter_request_delay_ms": 100,
        }
    else:
        defaults = {
            "port": "COM1",
            "slave_id": 1,
            "baud_rate": 9600,
            "parity": "N",
            "stop_bits": 1,
            "byte_size": 8,
            "timeout_seconds": 2,
            "retries": 1,
            "poll_interval_seconds": 15,
            "test_register": 19,
            "test_count": 1,
            "test_function": "input",
            "max_registers_per_request": 32,
            "inter_request_delay_ms": 100,
        }
    telemetry = build_ingeteam_telemetry()
    commands = build_ingeteam_commands()
    return [
        InverterModel(
            brand="Ingeteam",
            model=model,
            protocol=protocol,
            transport=transport,
            defaults=defaults,
            features=[
                "modbus unit commands profile",
                "monitoraggio live su input registers 30001+",
                "scrittura comandi su holding register 1000-1002",
                "potenza attiva via CMD 3 con payload 1000=command code, 1001=data1",
                "scrittura setpoint con function code 0x10 multi-register",
                "timing consigliato Ingeteam: >=100 ms tra frame",
                "setpoint attivi e reattivi",
                "battery control values",
                "profilo usabile anche via gateway modbus tcp/rs485",
                "necessaria scheda RS485 AAX0052 SAP 009524",
            ],
            telemetry_points=telemetry,
            command_points=commands,
        )
        for model in INGETEAM_MODELS
    ]
